In [3]:
import numpy as np
import pandas as pd
score = np.random.randint(50,101,size=(50,5))
score_pd = pd.DataFrame(score,columns=['國文','英文','數學','地理','歷史'],index=range(1,51))
score_pd

     國文   英文  數學  地理  歷史
1    63   59  69  87  83
2    73   89  69  88  75
3    52   89  64  91  78
4    81   71  96  89  75
5    52   81  89  68  94
6    72   76  59  69  88
7    82   95  88  69  97
8    79   61  62  52  50
9    98   97  51  89  75
10   72   92  96  81  95
11   76   90  67  52  97
12   75   65  52  65  72
13   52   86  81  90  83
14   68   78  85  94  88
15   91   60  68  91  93
16   93   68  54  83  83
17   79   61  71  65  98
18   51   79  69  95  78
19  100   78  62  81  89
20   54   75  57  75  65
21   64   84  74  95  58
22   60   63  78  79  75
23   82   78  92  61  98
24   95  100  61  76  63
25   63   79  71  65  57
26   67   84  56  64  62
27   92   54  50  72  82
28   84   92  54  87  69
29   92   66  85  81  78
30   91   75  74  62  93
31   83  100  54  50  70
32   93   56  50  72  55
33   61   87  79  84  52
34   84   60  87  50  60
35   55   96  80  64  97
36   84   58  65  68  65
37   99   85  72  86  83
38   83   53  71  77  68
39   79   62  63  64  73
40   95   84  89  97  93
41   65   90  58  95  63
42   89   96  93  65  64
43   91   62  61  69  62
44   83   63  78  98  81
45   81   90  99  70  51
46   87   89  58  90  58
47   55   87  68  86  96
48   79   58  74  85  85
49   51   86  94  55  94
50   96   67  54  79  59

In [4]:
score_pd.index.name="學號"
score_pd.columns.name="科目"
score_pd

科目   國文   英文  數學  地理  歷史
學號
1    63   59  69  87  83
2    73   89  69  88  75
3    52   89  64  91  78
4    81   71  96  89  75
5    52   81  89  68  94
6    72   76  59  69  88
7    82   95  88  69  97
8    79   61  62  52  50
9    98   97  51  89  75
10   72   92  96  81  95
11   76   90  67  52  97
12   75   65  52  65  72
13   52   86  81  90  83
14   68   78  85  94  88
15   91   60  68  91  93
16   93   68  54  83  83
17   79   61  71  65  98
18   51   79  69  95  78
19  100   78  62  81  89
20   54   75  57  75  65
21   64   84  74  95  58
22   60   63  78  79  75
23   82   78  92  61  98
24   95  100  61  76  63
25   63   79  71  65  57
26   67   84  56  64  62
27   92   54  50  72  82
28   84   92  54  87  69
29   92   66  85  81  78
30   91   75  74  62  93
31   83  100  54  50  70
32   93   56  50  72  55
33   61   87  79  84  52
34   84   60  87  50  60
35   55   96  80  64  97
36   84   58  65  68  65
37   99   85  72  86  83
38   83   53  71  77  68
39   79   62  63  64  73
40   95   84  89  97  93
41   65   90  58  95  63
42   89   96  93  65  64
43   91   62  61  69  62
44   83   63  78  98  81
45   81   90  99  70  51
46   87   89  58  90  58
47   55   87  68  86  96
48   79   58  74  85  85
49   51   86  94  55  94
50   96   67  54  79  59

In [5]:
display(score_pd['國文'][:10])
score_pd['數學'][:10]

學號
1     63
2     73
3     52
4     81
5     52
6     72
7     82
8     79
9     98
10    72
Name: 國文, dtype: int64

學號
1     69
2     69
3     64
4     96
5     89
6     59
7     88
8     62
9     51
10    96
Name: 數學, dtype: int64

In [6]:
score_pd['國文'][:10] + score_pd['數學'][:10]

學號
1     132
2     142
3     116
4     177
5     141
6     131
7     170
8     141
9     149
10    168
dtype: int64

In [7]:
score_pd['國文'][:10] + score_pd['英文'][:10] + score_pd['數學'][:10] + score_pd['地理'][:10] + score_pd['歷史'][:10]

學號
1     361
2     394
3     374
4     412
5     384
6     364
7     431
8     304
9     410
10    436
dtype: int64

In [8]:
score_pd['總分'] = score_pd[['國文','英文','數學','地理','歷史']].sum(axis=1)
score_pd
score_pd['平均'] = score_pd[['國文','英文','數學','地理','歷史']].mean(axis=1)
score_pd

科目   國文   英文  數學  地理  歷史   總分    平均
學號
1    63   59  69  87  83  361  72.2
2    73   89  69  88  75  394  78.8
3    52   89  64  91  78  374  74.8
4    81   71  96  89  75  412  82.4
5    52   81  89  68  94  384  76.8
6    72   76  59  69  88  364  72.8
7    82   95  88  69  97  431  86.2
8    79   61  62  52  50  304  60.8
9    98   97  51  89  75  410  82.0
10   72   92  96  81  95  436  87.2
11   76   90  67  52  97  382  76.4
12   75   65  52  65  72  329  65.8
13   52   86  81  90  83  392  78.4
14   68   78  85  94  88  413  82.6
15   91   60  68  91  93  403  80.6
16   93   68  54  83  83  381  76.2
17   79   61  71  65  98  374  74.8
18   51   79  69  95  78  372  74.4
19  100   78  62  81  89  410  82.0
20   54   75  57  75  65  326  65.2
21   64   84  74  95  58  375  75.0
22   60   63  78  79  75  355  71.0
23   82   78  92  61  98  411  82.2
24   95  100  61  76  63  395  79.0
25   63   79  71  65  57  335  67.0
26   67   84  56  64  62  333  66.6
27   92   54  50  72  82  350  70.0
28   84   92  54  87  69  386  77.2
29   92   66  85  81  78  402  80.4
30   91   75  74  62  93  395  79.0
31   83  100  54  50  70  357  71.4
32   93   56  50  72  55  326  65.2
33   61   87  79  84  52  363  72.6
34   84   60  87  50  60  341  68.2
35   55   96  80  64  97  392  78.4
36   84   58  65  68  65  340  68.0
37   99   85  72  86  83  425  85.0
38   83   53  71  77  68  352  70.4
39   79   62  63  64  73  341  68.2
40   95   84  89  97  93  458  91.6
41   65   90  58  95  63  371  74.2
42   89   96  93  65  64  407  81.4
43   91   62  61  69  62  345  69.0
44   83   63  78  98  81  403  80.6
45   81   90  99  70  51  391  78.2
46   87   89  58  90  58  382  76.4
47   55   87  68  86  96  392  78.4
48   79   58  74  85  85  381  76.2
49   51   86  94  55  94  380  76.0
50   96   67  54  79  59  355  71.0

In [9]:
score_pd['排名'] = score_pd['總分'].rank(method='min',ascending=False)
score_pd

科目   國文   英文  數學  地理  歷史   總分    平均    排名
學號
1    63   59  69  87  83  361  72.2  35.0
2    73   89  69  88  75  394  78.8  16.0
3    52   89  64  91  78  374  74.8  29.0
4    81   71  96  89  75  412  82.4   6.0
5    52   81  89  68  94  384  76.8  22.0
6    72   76  59  69  88  364  72.8  33.0
7    82   95  88  69  97  431  86.2   3.0
8    79   61  62  52  50  304  60.8  50.0
9    98   97  51  89  75  410  82.0   8.0
10   72   92  96  81  95  436  87.2   2.0
11   76   90  67  52  97  382  76.4  23.0
12   75   65  52  65  72  329  65.8  47.0
13   52   86  81  90  83  392  78.4  17.0
14   68   78  85  94  88  413  82.6   5.0
15   91   60  68  91  93  403  80.6  11.0
16   93   68  54  83  83  381  76.2  25.0
17   79   61  71  65  98  374  74.8  29.0
18   51   79  69  95  78  372  74.4  31.0
19  100   78  62  81  89  410  82.0   8.0
20   54   75  57  75  65  326  65.2  48.0
21   64   84  74  95  58  375  75.0  28.0
22   60   63  78  79  75  355  71.0  37.0
23   82   78  92  61  98  411  82.2   7.0
24   95  100  61  76  63  395  79.0  14.0
25   63   79  71  65  57  335  67.0  45.0
26   67   84  56  64  62  333  66.6  46.0
27   92   54  50  72  82  350  70.0  40.0
28   84   92  54  87  69  386  77.2  21.0
29   92   66  85  81  78  402  80.4  13.0
30   91   75  74  62  93  395  79.0  14.0
31   83  100  54  50  70  357  71.4  36.0
32   93   56  50  72  55  326  65.2  48.0
33   61   87  79  84  52  363  72.6  34.0
34   84   60  87  50  60  341  68.2  42.0
35   55   96  80  64  97  392  78.4  17.0
36   84   58  65  68  65  340  68.0  44.0
37   99   85  72  86  83  425  85.0   4.0
38   83   53  71  77  68  352  70.4  39.0
39   79   62  63  64  73  341  68.2  42.0
40   95   84  89  97  93  458  91.6   1.0
41   65   90  58  95  63  371  74.2  32.0
42   89   96  93  65  64  407  81.4  10.0
43   91   62  61  69  62  345  69.0  41.0
44   83   63  78  98  81  403  80.6  11.0
45   81   90  99  70  51  391  78.2  20.0
46   87   89  58  90  58  382  76.4  23.0
47   55   87  68  86  96  392  78.4  17.0
48   79   58  74  85  85  381  76.2  25.0
49   51   86  94  55  94  380  76.0  27.0
50   96   67  54  79  59  355  71.0  37.0

In [10]:
score_pd.sort_values(by='排名')

科目   國文   英文  數學  地理  歷史   總分    平均    排名
學號
40   95   84  89  97  93  458  91.6   1.0
10   72   92  96  81  95  436  87.2   2.0
7    82   95  88  69  97  431  86.2   3.0
37   99   85  72  86  83  425  85.0   4.0
14   68   78  85  94  88  413  82.6   5.0
4    81   71  96  89  75  412  82.4   6.0
23   82   78  92  61  98  411  82.2   7.0
19  100   78  62  81  89  410  82.0   8.0
9    98   97  51  89  75  410  82.0   8.0
42   89   96  93  65  64  407  81.4  10.0
44   83   63  78  98  81  403  80.6  11.0
15   91   60  68  91  93  403  80.6  11.0
29   92   66  85  81  78  402  80.4  13.0
30   91   75  74  62  93  395  79.0  14.0
24   95  100  61  76  63  395  79.0  14.0
2    73   89  69  88  75  394  78.8  16.0
47   55   87  68  86  96  392  78.4  17.0
13   52   86  81  90  83  392  78.4  17.0
35   55   96  80  64  97  392  78.4  17.0
45   81   90  99  70  51  391  78.2  20.0
28   84   92  54  87  69  386  77.2  21.0
5    52   81  89  68  94  384  76.8  22.0
46   87   89  58  90  58  382  76.4  23.0
11   76   90  67  52  97  382  76.4  23.0
48   79   58  74  85  85  381  76.2  25.0
16   93   68  54  83  83  381  76.2  25.0
49   51   86  94  55  94  380  76.0  27.0
21   64   84  74  95  58  375  75.0  28.0
17   79   61  71  65  98  374  74.8  29.0
3    52   89  64  91  78  374  74.8  29.0
18   51   79  69  95  78  372  74.4  31.0
41   65   90  58  95  63  371  74.2  32.0
6    72   76  59  69  88  364  72.8  33.0
33   61   87  79  84  52  363  72.6  34.0
1    63   59  69  87  83  361  72.2  35.0
31   83  100  54  50  70  357  71.4  36.0
50   96   67  54  79  59  355  71.0  37.0
22   60   63  78  79  75  355  71.0  37.0
38   83   53  71  77  68  352  70.4  39.0
27   92   54  50  72  82  350  70.0  40.0
43   91   62  61  69  62  345  69.0  41.0
39   79   62  63  64  73  341  68.2  42.0
34   84   60  87  50  60  341  68.2  42.0
36   84   58  65  68  65  340  68.0  44.0
25   63   79  71  65  57  335  67.0  45.0
26   67   84  56  64  62  333  66.6  46.0
12   75   65  52  65  72  329  65.8  47.0
32   93   56  50  72  55  326  65.2  48.0
20   54   75  57  75  65  326  65.2  48.0
8    79   61  62  52  50  304  60.8  50.0

In [11]:
def format60(v:int):
    if v >= 60:
        return '及格'
    else:
        return '不及格'        

score_pd[['國文','英文','數學','地理','歷史']].style.format(format60)

In [14]:
score_pd.style.highlight_between(left=0,right=59,color='yellow',subset=['國文','英文','數學','地理','歷史'])