In [10]:
import pandas as pd

dataFrame1 = pd.read_csv('上市公司資料.csv')
dataFrame2 = dataFrame1.reindex(columns=['公司名稱','產業別','營業收入-當月營收','營業收入-上月營收'])
dataFrame2.columns=['公司名稱','產業別','當月營收','上月營收']
dataFrame3 = dataFrame2.reindex(index=range(0,9))
dataFrame3

  公司名稱   產業別     當月營收     上月營收
0   亞泥  水泥工業  7069221  7864622
1   幸福  水泥工業   390053   326691
2   信大  水泥工業   478276   557403
3   東泥  水泥工業   176935   134470
4   大飲  食品工業    38696    29503
5   卜蜂  食品工業  2393814  2400161
6   泰山  食品工業  1054476  1023417
7   福壽  食品工業  1352250  1321525
8   台榮  食品工業   314062   294528